# Dependencies
markdown:            kramdown
highlighter:         rouge

gems:
  - jekyll-seo-tag

# Permalinks
permalink:           pretty
relative_permalinks: false

# Setup
title:               Tasos Keliris
tagline:             'if [ `whoami` == "root" ]; then echo "GameOver"; fi'
description:         'tasos keliris embedded security ICS koukouviou'
url:                 https://tkeliris.github.io
baseurl:             /

author:
name:                "Tasos Keliris"
url:                 "https://tkeliris.github.io"

# Custom vars
# Google services
google_analytics: UA-41615887-3